services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD-strongpass}
    env_file:
      - ../.env
    ports:
      - ${MONGO_PORT-27017}:27017
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT-8081}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD-strongpass}
      ME_CONFIG_MONGODB_URL: ${MONGO_URI-mongodb://root:strongpass@mongo:27017/}
    env_file:
      - ../.env
    depends_on:
      - mongo

volumes:
  mongo_data: